#!/bin/bash

python code/main.py \
       --train-mode train \
       --dataset cifar10 \
       --net convmedbig_flat_2_2_4_250 \
       --train-batch 100 --test-batch 100 \
       --train-eps 0.00784313725 --start-eps-factor 1.05 --eps-factor 1.1 \
       --layers -2 -1 2 4 6 \
       --train-att-n-steps 8 --train-att-step-size 0.25 --test-att-n-steps 40 --test-att-step-size 0.035 \
       --opt sgd --lr 0.03 --lr-step 10 --lr-factor 0.5 --lr-layer-dec 0.75 \
       --mix --mix-epochs 60 --n-epochs 200 \
       --l1-reg 0.00001 --relu-stable 0.005 --relu-stable-factor 1.5 \
       --test-freq 50
